### ISSUE TITLE
Allow ```ts codeblocks in asciidoc

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#29]
This is a valid snippet of asciidoc from _Learning TypeScript_'s source:

    ==== TypeScript in Action
    
    Take a look at this code snippet:
    
    ```ts
    const firstName = "Georgia";
    const nameLength = firstName.length();
    //                           ~~~~~~
    // This expression is not callable.
    ```

literate-ts won't recognize that code snippet.

```shell
$ literate-ts ch*.asciidoc
Logging details to /tmp/tmp-17593svikXHQlVyir/log.txt
Verifying with TypeScript 4.6.3
ch01-from_javascript_to_typescript.asciidoc 0/0 passed
```

Would you accept a PR allowing it to? 🌹

**Comment by danvk** [comment]
Yes! Does O'Reilly AsciiDoc accept that format now? I remember when I was writing it had to be

```
[source,ts]
----
// your code here
----
```

There's already code in this repo to parse Markdown, so hopefully that can be reused.
