### ISSUE TITLE
Switch to filename:line:col output format

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#31]
Here's an example current error message:

```
ch02-the_type_system-40: Unexpected TypeScript error: 0:0-5: BigInt literals are not available when targeting lower than ES2020.
```

In VS Code, you can Ctrl+Click on file specifiers that include line and column. It's very useful. 

Proposal: switch the id printed for a file & line to reference the offending snippet:

```
./ch02-the_type_system.asciidoc:40:0: Unexpected TypeScript error: 0:0-5: BigInt literals are not available when targeting lower than ES2020.
```

**Comment by danvk** [comment]
Yes, PR please!

I believe `ch02-the_type_system-40` is a name for the code sample that literate-ts synthesized. That identifier is useful for some directives (`verifier:prepend-id-to-following:ID`). But regardless, we could print the code location _and_ the identifier.
