### ISSUE TITLE
Add a CLI option for only running on a subset of a file's code snippets

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#38]
Suppose you have a file with several dozen code snippets. Running literate-ts on the file can take many seconds. That time spend can be inconvenient if you've only changed one snippet.

Can we have some kind of CLI option that allows specifying a line number? Maybe, `-l`/`--line` to specify a `number[]` of lines to check in any input file?

```ts
literate-ts file.asciidoc -l 12 --line 34
```

**Comment by danvk** [comment]
There's an existing `--filter` option that filters based on the source ID. This is file name + line number, unless you set it explicitly, so I think that should meet your needs?

**Comment by JoshuaKGoldberg** [comment]
Aha! I missed the CLI options. Will send a docs PR, thanks!
