### ISSUE TITLE
Add a verifier directive for a local file import

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#39]
`include-node-module:module-name` exists today for including a Node module in the type checking of a snippet. But, what if we want to include some fictional local file?

Here's a snippet from _Learning TypeScript_:

> For reference, this module file imports a `value` from a sibling `./values` file and exports a `doubled` variable.
> 
> ```ts
> import { value } from './values';
> 
> export const doubled = value * 2;
> ```

I'd like to be able to have literate-ts know that `./values` is a file that contains `export const value: number`.

Perhaps a directive like `include-dts-file:./values.d.ts`?

**Comment by danvk** [comment]
Could you do this with a hidden (commented out) code sample that includes something like

```ts
declare module "./values" {
  export const doubled: number;
}
```

Even if that doesn't work, this seems like a reasonable feature request. I guess I'd just caution that it would be better for readers if the contents of that module were somewhere in print, rather than being a mystery.

**Comment by danvk** [comment]
With #150 you can do this with the `prepend-with-file` directive:

```asciidoc
For reference, this module file imports a value from a sibling ./values file and exports a doubled variable.

////
// verifier:prepend-as-file:values.ts
[source,ts]
----
export const value = Math.PI;
----
////

[source,ts]
----
import { value } from './values';

export const doubled = value * 2;
----
```
