### ISSUE TITLE
prepend-to-following doesn't produce expected errors in first snippet

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#41]
This pair of code snippets is meant to show TypeScript giving an error when in script (rather than module) mode:

> // verifier:prepend-to-following
> ```ts
> // a.ts
> const shared = "Cher";
> //    ~~~~~~
> // Cannot redeclare block-scoped variable 'shared'.
> ```
> 
> ```ts
> // b.ts
> const shared = "Cher";
> //    ~~~~~~
> // Cannot redeclare block-scoped variable 'shared'.
> ```

But, while the first snippet is prepended to the second, the first snippet isn't included in the second. Maybe this is a feature request for a `merge-with-following` verifier?

**Comment by danvk** [comment]
Is the proposal here to write two different files to the output directory?

If you're OK with concatenating files, you can achieve the double failure using `prepend-id-to-following`:

```asciidoc
// verifier:prepend-id-to-following:sample-b
[[sample-a]]
[source,ts]
----
// a.ts
const shared = "Cher";
//    ~~~~~~
// Cannot redeclare block-scoped variable 'shared'.
----

// verifier:reset
// verifier:prepend-id-to-following:sample-a
[[sample-b]]
[source,ts]
----
// b.ts
const shared = "Cher";
//    ~~~~~~
// Cannot redeclare block-scoped variable 'shared'.
----

```

**Comment by JoshuaKGoldberg** [comment]
That should work, thanks!
