### ISSUE TITLE
No way to set a snippet ID in .asciidoc file

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#43]
> To give a code sample an ID, use an HTML comment starting with a #:
> 
> This sample has an ID of `Point`:
> 
> 
> ```ts
> type Point = [number, number];
> ```

`<!--` is seen as text in .asciidoc files as far as I can tell. Can we have `// ` comment support for this?

**Comment by danvk** [comment]
Oh, those instructions are for Markdown. For Asciidoc you use the normal convention for naming (`[[name]]`):

```asciidoc
This sample has an ID of `Point`:

[[Point]]
[source,ts]
----
type Point = [number, number];
----
```

The instructions should include a specific mention of that, though.
