### ISSUE TITLE
VS Code extension?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danvk/literate-ts#44]
Apologies if this is a feature request that belongs in a new repository 😅 but I'm finding that I'm constantly re-running this tool in the CLI. What are your thoughts on creating a VS Code extension? Are there any structural changes in this repo that you think would be necessary to support one?

**Comment by danvk** [comment]
An extension would be great, but I think it would belong in a different repo. We might need to support running literate-ts as more of a service than a CLI app.

**Comment by danvk** [comment]
It's not quite an extension, but I've had pretty good luck running literate-ts as a task in VS Code with an appropriate problem matcher: https://github.com/danvk/literate-ts#vs-code-integration

<img width="623" alt="image" src="https://github.com/danvk/literate-ts/assets/98301/ec4abf74-6665-42cb-aa86-435d9cb04955">

This really makes you want #99 for improved error span reporting.

**Comment by danvk** [comment]
With #104 and a VS Code task, I actually don't see much value in creating a full-on extension. The task works well enough. I'm going to close this out.

<img width="743" alt="image" src="https://github.com/danvk/literate-ts/assets/98301/acb1df93-faa2-4a34-a0a6-08f36f8b99ca">
